sudo: required
services:
 - docker

before_install:
 - docker build -t mkerimbay/django-react-frontend ./frontend
	
script:
 - docker run mkerimbay/django-react-frontend npm test -- --coverage
	
after_success:
 - docker built -t mkerimbay/django-react-frontend ./frontend
 - docker built -t mkerimbay/django-react-backend ./backend
# Push images to my Docker-hub account
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 - docker push mkerimbay/django-react-frontend
 - docker push mkerimbay/django-react-backend
	